%name-prefix "MBASIC_" 
%define parse.error verbose

%{

#include <iostream>
#include <string>
#include <sstream>
#include <memory>
using namespace std;

#include "common.h"
#include "basalt.h"

#define YYDEBUG 1

static bool g_needsNewLine = false;

namespace std {
  template<typename T, typename... Args>
  std::unique_ptr<T> make_unique(Args&&... args) {
      return std::unique_ptr<T>(new T(std::forward<Args>(args)...));
  }
}

static AST::ExprList * ConcatExprLists(AST::ExprList * a, AST::ExprList * b)
{
  if (b == nullptr)
    return a;

  for (auto & r : *b) {
    if (r != nullptr)
      a->push_back(r);
  }

  return a;
}



extern void MBASIC_SetRemMode();

%}

%union {
  char          cval;
  unsigned int  uval;
  int           ival;
  std::string * sval;
  UnsignedList * ulist;

  Variable             * varval;
  AST::VariableDefExpr * vardef;
  AST::VariableRefExpr * varref;

  SingleFloat * sfloat;
  DoubleFloat * dfloat;

  AST::Expr     * expr;
  AST::ExprList * exprlist;
}

%token EOL_TOKEN
%token EOF_TOKEN

// operators
%token GREATERTHANEQUAL
%token LESSTHANEQUAL
%token NOT_EQUAL
%token AND_TOKEN

// functions
%token CHR_TOKEN
%token INT_TOKEN
%token LEFT_TOKEN 
%token MID_TOKEN
%token RIGHT_TOKEN
%token SQR_TOKEN
%token STR_TOKEN
%token TAB_TOKEN

// commands
%token CLEAR_TOKEN
%token DEF_TOKEN
%token DIM_TOKEN
%token ELSE_TOKEN
%token END_TOKEN
%token FOR_TOKEN
%token IF_TOKEN
%token GOSUB_TOKEN
%token GOTO_TOKEN
%token INPUT_TOKEN
%token LET_TOKEN
%token NEXT_TOKEN
%token OR_TOKEN
%token ON_TOKEN
%token PRINT_TOKEN
%token REM_TOKEN
%token RETURN_TOKEN
%token RUN_TOKEN 
%token STEP_TOKEN
%token SYSTEM_TOKEN
%token STOP_TOKEN
%token THEN_TOKEN
%token TO_TOKEN
%token USING_TOKEN
%token WIDTH_TOKEN

// other lexemes
%token <sval>   IDENTIFIER QUOTED_STRING DEF_INTEGER
%token <sval>   INTEGER_VARNAME STRING_VARNAME SINGLE_VARNAME DOUBLE_VARNAME
%token <ival>   INTEGER 
%token <dfloat> DOUBLE 
%token <sfloat> SINGLE

// rules
%type <exprlist>    MBASIC_file line opt_statement_list statement_list statement

%type <exprlist>    DIM_statement dim_var_list

%type <exprlist>    LET_statement assign_expression 

%type <exprlist>    FOR_statement

%type <exprlist>    GOTO_statement

%type <exprlist>    PRINT_statement print_expression_list 
%type <expr>        print_expression

%type <expr>        WIDTH_statement

%type <expr>        AND_expression NOT_expression compare_expression ADD_expression
%type <expr>        MULT_expression NEGATE_expression POWER_expression subexpression

%type <sval>        opt_line_number line_number
%type <expr>        expression const_expr value array_or_func_arg 
%type <varref>      var_ref
%type <varval>      var_name
%type <ival>        integer
%type <exprlist>    array_or_func_spec array_or_func_args 

%%

MBASIC_file:  line              
                {
                  ConcatExprLists(&g_expressions, $1);
                }
              | MBASIC_file line
                {
                  ConcatExprLists(&g_expressions, $2);
                } 
              ;

/*********************************************************F

 line              

 *********************************************************/ 

line:     opt_line_number
            {
              AST::LineMarkerExpr * marker; 
              if ($1 == nullptr)
                marker = new AST::LineMarkerExpr(g_lineNumber);
              else {
                marker = new AST::LineMarkerExpr(g_lineNumber, *$1);
                delete $1;
              }
              marker->m_line = g_application.m_line;
              $<expr>$ = marker;
              g_currentSourceFileMarker = marker;
            }
          opt_statement_list eol
            {
              $$ = new AST::ExprList($<expr>2);
              ConcatExprLists($$, $3);
            }
          ;

opt_line_number: /* empty */
                    { $$ = nullptr; }
                 | line_number
                    { $$ = $1; }
                 ;

line_number:    integer
                    {
                      std::stringstream strm;
                      strm << $1;
                      $$ = new std::string(strm.str());
                    }
                 ; 

integer:    INTEGER
              {
                $$ = $1;
              }
            | DEF_INTEGER
              {
                $$ = atoi($1->c_str());
                delete $1;
              }
            ;                 

opt_statement_list : /* empty */
                      {
                        $$ = nullptr;
                      }
                   | statement_list
                      {
                        $$ = $1;
                      }
                   ;

statement_list : statement
                  {
                    $$ = $1;
                  }   
               | statement_list ':' statement
                  {
                    if ($1 == nullptr)
                      $$ = $1;
                    else {  
                      ConcatExprLists($1, $3);
                      delete $3;
                      $$ = $1;
                    }
                  }   
               ;

statement:     CLEAR_statement
                  {
                    $$ = nullptr;
                  }
               | DEF_statement
                  {
                    $$ = nullptr;
                  }   
               | DIM_statement
                  {
                    $$ = $1;
                  }   
               | END_statement
                  {
                    $$ = nullptr;
                  }   
               | FOR_statement
                  {
                    $$ = $1;
                  }
               | GOTO_statement
                  {
                    $$ = $1;
                  }
               | GOSUB_statement
                  {
                    $$ = nullptr;
                  }
               | IF_statement
                  {
                    $$ = nullptr;
                  }
               | INPUT_statement
                  {
                    $$ = nullptr;
                  }
               | LET_statement
                  {
                    $$ = $1;
                  }
               | NEXT_statement
                  {
                    $$ = nullptr;
                  }
               | ON_statement
                  {
                    $$ = nullptr;
                  }   
               | PRINT_statement 
                  {
                    $$ = $1;
                  }
               | REM_statement
                  {
                    $$ = nullptr;
                  }
               | RUN_statement
                  {
                    $$ = nullptr;
                  }
               | RETURN_statement
                  {
                    $$ = nullptr;
                  }
               | STOP_statement
                  {
                    $$ = nullptr;
                  }
               | SYSTEM_statement
                  {
                    $$ = nullptr;
                  }
               | WIDTH_statement
                  {
                    $$ = nullptr; //new AST::ExprList($1);
                  }
               | error /* bison error handler */   
                  {
                    $$ = nullptr;
                  }
               ;

eol:    EOL_TOKEN
        | EOF_TOKEN
          { return 0; }  // yes, this is a return!
        ;               

/********************************************************* 

  CLEAR

 *********************************************************/ 

CLEAR_statement: CLEAR_TOKEN expression
                 ;

/********************************************************* 

  DEF

 *********************************************************/ 

DEF_statement:  DEF_TOKEN IDENTIFIER opt_def_args '=' expression 
                ;

opt_def_args: /* empty */
              | '(' def_arg_list ')'
              ;

def_arg_list: IDENTIFIER 
              | def_arg_list ',' IDENTIFIER
              ;              

/********************************************************* 

  DIM

 *********************************************************/ 

DIM_statement:  DIM_TOKEN dim_var_list
                  {
                    $$ = $2;
                  }
                ;

dim_var_list: var_ref
                {
                  $$ = new AST::ExprList($1);
                }
              | dim_var_list ',' var_ref 
                {
                  $$ = $1;
                  $$->push_back($3);
                }
              ;

/*********************************************************

 END

 *********************************************************/ 
              
END_statement:  END_TOKEN
                ;

/********************************************************* 

 FOR/NEXT/STEP

 *********************************************************/ 

FOR_statement: FOR_TOKEN var_ref '=' expression TO_TOKEN expression opt_STEP_statement
                {
                  $$ = new AST::ExprList($2);
                }
                ;

NEXT_statement: NEXT_TOKEN opt_varname
                ;

opt_varname:    /* empty */
                | var_ref
                ;                

opt_STEP_statement: /* empty */
                    | STEP_TOKEN expression
                    ;

/*********************************************************

 GOSUB/RETURN

 *********************************************************/ 
              
GOSUB_statement:  GOSUB_TOKEN line_number
                ;

RETURN_statement:  RETURN_TOKEN
                ;

/*********************************************************

 GOTO

 *********************************************************/ 
              
GOTO_statement: GOTO_TOKEN line_number
                  {
                    g_gotoTargets.insert(*$2);
                    $$ = new AST::ExprList(new AST::GotoExpr(*$2));
                  }
                ;

/*********************************************************

 IF/THEN/ELSE

 *********************************************************/ 

IF_statement: IF_TOKEN expression THEN_TOKEN conditional_clause opt_ELSE_statement
              ;

opt_ELSE_statement:   /* empty */
                      | ELSE_statement
                      ;              

ELSE_statement: ELSE_TOKEN conditional_clause
                ;

conditional_clause:   line_number
                      | statement_list 
                      ; 

/********************************************************* 

 INPUT  

 *********************************************************/ 

 INPUT_statement: INPUT_TOKEN QUOTED_STRING ';' input_var_list
                  | INPUT_TOKEN input_var_list
                  ;

 input_var_list:  input_var
                  | input_var_list ',' input_var
                  ;

 input_var:       var_ref
                  ;       

/********************************************************* 

 LET              

 *********************************************************/ 

LET_statement:  opt_LET_TOKEN assign_expression
                {
                  $$ = $2;
                }
                ;

opt_LET_TOKEN:  /* empty */
                | LET_TOKEN
                ;

assign_expression:  var_ref '=' expression
                      {
                        if ($1 == nullptr)
                          $$ = nullptr;
                        else {  
                          $$ = new AST::ExprList();
                          $$->push_back(new AST::VariableDefExpr($1->m_variable, $1->GetDim(), true));
                          $$->push_back(new AST::BinaryExpr('=', $1, $3));
                        }
                      }
                    ;

/********************************************************* 

 ON
 
 *********************************************************/ 

ON_statement:    ON_TOKEN expression GOTO_TOKEN line_number opt_on_list
                  ;

opt_on_list:     /* empty */
                  | ',' line_number opt_on_list
                  ;                 

/********************************************************* 

 PRINT              
 
 *********************************************************/   

PRINT_statement:  print_keyword
                    {
                      g_needsNewLine = true;
                    }
                  opt_USING
                    {
                    }  
                  print_expression_list
                    {
                      if (!g_needsNewLine)
                        $$ = $5;
                      else {
                        if ($5 == nullptr)
                          $$ = new AST::ExprList();
                        else
                          $$ = $5;
                        $$->push_back(new AST::BIFExpr("print_eol", nullptr));
                      }
                    }
                  ;

print_keyword:   PRINT_TOKEN
                 | '?'
                    { 
                      Warning(eWarning_PrintUsingQuestionMark, "question mark PRINT not supported in selected language profile"); 
                    }
                 ;

opt_USING:      /* empty */
                | USING_TOKEN expression ';'
                ;                       

print_expression_list: /* empty */
                          {
                            $$ = new AST::ExprList;
                            g_needsNewLine = true;
                          }  
                       | print_expression_list print_expression
                          {
                            if ($2 != nullptr)
                              $1->push_back($2);
                            $$ = $1;
                          }
                       ;

print_expression:      expression
                          {
                            g_needsNewLine = true;
                            AST::ExprList * args = new AST::ExprList($1);
                            $$ = new AST::BIFExpr("print_expr", args);
                          }
                       | ',' 
                          {
                            g_needsNewLine = false;
                            $$ = new AST::BIFExpr("print_tab", nullptr);
                          }
                       | ';'
                          {
                            g_needsNewLine = false;
                            $$ = nullptr;
                          }
                       ;                           

/********************************************************* 

 REM              
 
 *********************************************************/ 

REM_statement: rem_keyword
                  {
                    MBASIC_SetRemMode();
                  }
               ;

 rem_keyword: REM_TOKEN
              | '\''
                { 
                  Warning(eWarning_RemUsingQuote, "single quote REM not supported in selected language profile"); 
                }
              ;              

/********************************************************* 

 RUN
 
 *********************************************************/ 

RUN_statement: RUN_TOKEN QUOTED_STRING
              ;

/********************************************************* 

 STOP              
 
 *********************************************************/ 

STOP_statement: STOP_TOKEN
                ;

/********************************************************* 

 SYSTEM              
 
 *********************************************************/ 

SYSTEM_statement: SYSTEM_TOKEN
                ;

/********************************************************* 

 WIDTH              
 
 *********************************************************/ 

WIDTH_statement: WIDTH_TOKEN integer
                  {
                  }
               ;

/********************************************************* 

 expression              

 *********************************************************/ 

expression: AND_expression OR_TOKEN expression
              {
                $$ = new AST::BinaryExpr('|', $1, $3);
              }
            | AND_expression
              {
                $$ = $1;
              }  
            ;

AND_expression: NOT_expression AND_TOKEN AND_expression
                  {
                    $$ = new AST::BinaryExpr('&', $1, $3);
                  }
                | NOT_expression
                  {
                    $$ = $1;
                  }
                ;

NOT_expression: '-' compare_expression
                  {
                    $$ = nullptr;
                  }
                | compare_expression
                  {
                    $$ = $1;
                  }
                ;

compare_expression: ADD_expression '=' compare_expression
                      {
                        $$ = nullptr;
                      }
                    | ADD_expression NOT_EQUAL compare_expression
                      {
                        $$ = nullptr;
                      }
                    | ADD_expression '>' compare_expression
                      {
                        $$ = new AST::BinaryExpr('>', $1, $3);
                      }
                    | ADD_expression GREATERTHANEQUAL compare_expression
                      {
                        $$ = nullptr;
                      }
                    | ADD_expression '<' compare_expression
                      {
                        $$ = new AST::BinaryExpr('<', $1, $3);
                      }
                    | ADD_expression LESSTHANEQUAL compare_expression
                      {
                        $$ = nullptr;
                      }
                    | ADD_expression 
                      {
                        $$ = $1;
                      }
                    ;

ADD_expression: MULT_expression '+' ADD_expression
                  { 
                    $$ = new AST::BinaryExpr('+', $1, $3);
                  }
                | MULT_expression '-' ADD_expression
                  { 
                    $$ = new AST::BinaryExpr('-', $1, $3);
                  }
                | MULT_expression
                  {
                    $$ = $1;
                  }  
                ;

MULT_expression:  NEGATE_expression '*' MULT_expression
                    { 
                      $$ = new AST::BinaryExpr('*', $1, $3);
                    }
                  | NEGATE_expression '/' MULT_expression
                    { 
                      $$ = new AST::BinaryExpr('/', $1, $3);
                    }  
                  | NEGATE_expression
                    {
                      $$ = $1;  
                    } 
                  ;   
                          
NEGATE_expression:  '-' POWER_expression
                      {
                        $$ = nullptr; //new AST::Int16UnaryExpr('-', $2);
                      }  
                    | POWER_expression
                      {
                        $$ = $1;
                      }
                    ;  

POWER_expression: POWER_expression '^' subexpression
                    {
                      $$ = new AST::BinaryExpr('^', $1, $3);
                    }
                  | subexpression
                      {
                        $$ = $1;
                      }
                  ;

subexpression: '(' expression ')'
                  {
                    $$ = $2;
                  }
                | value
                  {
                    $$ = $1;
                  }
                ;                           

value:          var_ref
                  {
                    $$ = $1;
                  }
                | CHR_TOKEN '(' expression ')'  
                  {
                    $$ = nullptr;
                  }
                | INT_TOKEN '(' expression ')'  
                  {
                    $$ = nullptr;
                  }
                | LEFT_TOKEN '(' expression ',' expression ')'  
                  {
                    $$ = nullptr;
                  }
                | MID_TOKEN '(' expression ',' expression ',' expression ')'  
                  {
                    $$ = nullptr;
                  }
                | RIGHT_TOKEN '(' expression ',' expression ')'  
                  {
                    $$ = nullptr;
                  }
                | STR_TOKEN '(' expression ')'  
                  {
                    $$ = nullptr;
                  }
                | SQR_TOKEN '(' expression ')'  
                  {
                    $$ = nullptr;
                  }
                | TAB_TOKEN '(' expression ')'  
                  {
                    $$ = nullptr;
                  }
                | const_expr
                  {
                    $$ = $1;
                  }
                ;  

/********************************************************* 

var or array ref              
 
 *********************************************************/

var_ref : var_name
            {
              g_languageProfile->NormalizeVariableName(*$1, 0);
              $$ = new AST::VariableRefExpr(*$1, nullptr, true);
              delete $1;
            }
          | var_name array_or_func_spec
            {
              g_languageProfile->NormalizeVariableName(*$1, $2->size());
              $$ = new AST::VariableRefExpr(*$1, $2, true);
              delete $1;
            }
          ;

var_name: IDENTIFIER
            {
              Variable::Type type = g_languageProfile->GetDefaultNumericType();
              switch (type) {
                case Variable::Type::eInt16:
                  $$ = new Variable(Variable::eInt16, *$1 + "%");
                  break;                
                case Variable::Type::eSingle:
                  $$ = new Variable(Variable::eSingle, *$1 + "!");
                  break;
                default:
                  InternalError("unknown default numeric type " << (int)type);
                  exit(1);
              }   
              delete $1;
            }
          | INTEGER_VARNAME
            {
              $$ = new Variable(Variable::eInt16, *$1);
              delete $1;
            }
          | STRING_VARNAME
            {
              $$ = new Variable(Variable::eString, *$1);
              delete $1;
            }
          | SINGLE_VARNAME
            {
              $$ = new Variable(Variable::eSingle, *$1);
              delete $1;
            }
          | DOUBLE_VARNAME
            {
              $$ = new Variable(Variable::eDouble, *$1);
              delete $1;
            }
          ;

array_or_func_spec: '(' array_or_func_args ')'
                      {
                        $$ = $2;
                      }
                    ; 

array_or_func_args: array_or_func_arg 
                      {
                        $$ = new AST::ExprList($1);
                      }
                    | array_or_func_args ',' array_or_func_arg   
                      {
                        $$ = $1;
                        $$->push_back($3);
                      }
                    ;

array_or_func_arg:  expression
                      {
                        $$ = $1;
                      }
                    ;

/********************************************************* 

 miscellaneous              
 
 *********************************************************/ 

const_expr: INTEGER
              {
                $$ = new AST::ConstantInt16Expr($1);
              }
            | DOUBLE
              {
                $$ = nullptr;
              }
            | SINGLE
              {
                $$ = nullptr;
              }
            | DEF_INTEGER  
              {
                Variable::Type type = g_languageProfile->GetDefaultNumericType();
                switch (type) {
                  case Variable::Type::eInt16:
                    $$ = new AST::ConstantInt16Expr(atoi($1->c_str()));
                    break;                
                  case Variable::Type::eSingle:
                    $$ = new AST::ConstantSingleExpr(atof($1->c_str()));
                    break;
                  default:  
                    InternalError("unknown default numeric type " << (int)type);
                    exit(1);
                }
                delete $1;   
              }
            | QUOTED_STRING
              {
                g_stringConstants.insert(*$1);
                $$ = new AST::ConstantStringExpr(*$1);
                delete $1;
              }
            ;
