%define api.prefix {mbasic_}
%define parse.error verbose

%{

#include <iostream>
#include <string>
#include <sstream>
#include <memory>
#include <deque>
using namespace std;

#include "common.h"
#include "basalt.h"

#define YYDEBUG 1

static unsigned g_lineNumber = 1;     // parsed source line number

extern void MBASIC_SetRemMode();

typedef std::deque<std::string> OnRefList;

#define ParserError(code, expr) \
do { std::stringstream strm; strm << expr; \
  g_application.ParserErrorInternal(ErrorCode::code, strm.str()); \
} while (0)

// used by parser to display error

void mbasic_error(const char * msg)
{
  ParserError(eError_Parser, msg);
}


static AST::NumericExpr * CreateConstant(VarType type, const std::string & val)
{
  switch (type) {
    case VarType::eInt16:
      return AST::Int16Constant::Create(val);
    case VarType::eInt32:
      return AST::Int32Constant::Create(val);
    case VarType::eSingle:
      return AST::SingleConstant::Create(val);
    case VarType::eDouble:
      return AST::DoubleConstant::Create(val);
    case VarType::eString:
    case VarType::eNone:
      break;
  }
  return nullptr;
}

static void UseNumericGlobalVar(AST::NumericVarRef & var, bool left, bool right)
{
  std::string synonym = 
          AST::g_parser->DefineVar(
                        var.GetName(),
                        var.GetOriginalName(), 
                        var.GetType(),
                        left  ? g_lineNumber : -1,
                        right ? g_lineNumber : -1
                        );

  if (!synonym.empty())                      
    ParserError(eWarning_VarIsSynonym,
                "'" << var.GetOriginalName() << "' & '" << synonym << "'");
}

static void UseStringGlobalVar(AST::StringVarRef & var, bool left, bool right)
{
  std::string synonym = 
          AST::g_parser->DefineVar(
                        var.GetName(),
                        var.GetOriginalName(), 
                        var.GetType(),
                        left  ? g_lineNumber : -1,
                        right ? g_lineNumber : -1
                        );
  if (!synonym.empty())                      
    ParserError(eWarning_VarIsSynonym,
                "'" << var.GetOriginalName() << "' & '" << synonym << "'");
}

%}

%union {
  char          cval;
  unsigned int  uval;
  int           ival;
  std::string * sval;

  AST::Node            * node;
  AST::Expr            * expr;
  AST::ExprList        * exprList;
  AST::SourceLine      * sourceLine;
  AST::Statement       * statement;
  AST::StatementList   * statementList;
  AST::NumericOperator * oper;
  AST::IfConditional   * ifcond;
  AST::NumericExpr     * numexpr;
  AST::NumericVarRef   * numvarref;

  AST::StringExpr      * strexpr;
  AST::StringVarRef    * strvarref;

  AST::OnRefList       * onreflist;

  SingleFloat * sfloat;
  DoubleFloat * dfloat;
}

%token EOL_TOKEN
%token EOF_TOKEN

// operators
%token GREATERTHANEQUAL
%token LESSTHANEQUAL
%token NOT_EQUAL
%token AND_TOKEN

// functions
%token ABS_TOKEN
%token CHR_TOKEN
%token INT_TOKEN
%token LEFT_TOKEN
%token LEN_TOKEN 
%token MID_TOKEN
%token RIGHT_TOKEN
%token RND_TOKEN
%token SQR_TOKEN
%token STR_TOKEN
%token TAB_TOKEN

// commands
%token CLEAR_TOKEN
%token DEF_TOKEN
%token DIM_TOKEN
%token ELSE_TOKEN
%token END_TOKEN
%token FOR_TOKEN
%token IF_TOKEN
%token GOSUB_TOKEN
%token GOTO_TOKEN
%token INPUT_TOKEN
%token LINE_TOKEN
%token LET_TOKEN
%token NEXT_TOKEN
%token OR_TOKEN
%token ON_TOKEN
%token PRINT_TOKEN
%token REM_TOKEN
%token RETURN_TOKEN
%token RUN_TOKEN 
%token STEP_TOKEN
%token SYSTEM_TOKEN
%token STOP_TOKEN
%token THEN_TOKEN
%token TO_TOKEN
%token USING_TOKEN
%token WIDTH_TOKEN

// other lexemes
%token <sval>   IDENTIFIER QUOTED_STRING DEF_INTEGER
%token <sval>   INTEGER_VARNAME STRING_VARNAME SINGLE_VARNAME DOUBLE_VARNAME COMMENT
%token <ival>   INTEGER  
%token <dfloat> DOUBLE 
%token <sfloat> SINGLE

// rules
//%type <sourceLine>    line 
%type <statementList> opt_statement_list statement_list

%type <statement>    statement //statement2
%type <statement>    DIM_statement PRINT_statement WIDTH_statement
%type <statement>    LET_statement FOR_statement GOTO_statement
%type <statement>    IF_statement REM_statement NEXT_statement
%type <statement>    GOSUB_statement RETURN_statement 
%type <exprList>     dim_var_list
%type <expr>         assign_expression 
%type <ifcond>       conditional_clause 
%type <ifcond>       opt_ELSE_statement ELSE_statement

// not yet implemented
%type <statement> ON_statement CLEAR_statement DEF_statement INPUT_statement
%type <statement> LINE_statement STOP_statement RUN_statement

%type <exprList> print_expression_list 
%type <expr>     print_expression

%type <sval>        opt_line_number line_number  opt_COMMENT
%type <ival>        integer

%type <onreflist>   opt_on_list

%type <numvarref>  numeric_var_ref numeric_var_name opt_varname 
%type <numexpr>    expression subexpression numeric_const_expr 
%type <numexpr>    numeric_value array_or_func_arg 
%type <numexpr>    AND_expression NOT_expression numeric_compare_expression ADD_expression
%type <numexpr>    MULT_expression NEGATE_expression POWER_expression string_compare_expression 
%type <numexpr>    if_expression opt_STEP_statement

%type <strvarref>  string_var_ref string_var_name
%type <strexpr>    string_value string_expression string_const_expr 
%type <strexpr>    string_subexpression 

%%

file:     /* empty */
          | file line
          ;

/*********************************************************F

 line              

 *********************************************************/ 

line:     opt_line_number 
              {
                if (!AST::g_parser->StartLine($1)) {
                  ParserError(Error_DuplicateLineNumber,
                              "duplicate BASIC line number '" << AST::g_parser->m_basicLineNumber << "' on lines " << AST::g_parser->m_lexLineNumber << " & " << AST::g_parser->m_lineNumberInfo[AST::g_parser->m_basicLineNumber]);
                }
                $<sourceLine>$ = new AST::SourceLine(
                      AST::g_parser->m_lexLineNumber,
                      AST::g_parser->m_basicLineNumber, 
                      g_application.GetCurrentLine()
                      );
                g_lineNumber = AST::g_parser->m_lexLineNumber;
                g_application.SetStatementStart();
              }
          opt_statement_list 
            {
              if (($3 == nullptr) && ($<sourceLine>2->GetBasicLineNumber().empty())) {
                delete $<sourceLine>2;
                delete $3;
              }
              else {
                AST::SourceLine * line = $<sourceLine>2;
                if ($3 != nullptr)
                  line->m_statements.reset($3);
                AST::g_parser->m_program.Append(line);
              }
            }
          eol
          ;

opt_line_number: /* empty */
                    { 
                      $$ = nullptr;
                    }
                 | line_number
                    { 
                      $$ = $1;
                    }
                 ;

line_number:    DEF_INTEGER
                    {
                      $$ = new std::string(*$1);
                      delete $1;
                    }
                 ; 

integer:    INTEGER
              {
                $$ = $1;
              }
            | DEF_INTEGER
              {
                $$ = strtol($1->c_str(), NULL, 10);
                delete $1;
              }  
            ;                 

opt_statement_list : /* empty */
                      {
                        $$ = nullptr;
                      }
                   | statement_list
                      {
                        $$ = $1;
                      }
                   ;

statement_list : statement
                  {
                    $$ = new AST::StatementList();
                    if (($1 != nullptr) && $1->m_text.empty())
                      $1->m_text = g_application.GetStatement();
                    $$->Append($1);
                  }   
               | statement_list ':'
                  {
                    g_application.SetStatementStart();
                  } 
                 statement
                  {
                    if ($4 != nullptr) {
                      if ($4->m_text.empty())
                        $4->m_text = g_application.GetStatement();
                      $1->Append($4);
                    }
                    $$ = $1;
                  }   
               ;

//statement2:   { 
//              }
//              statement
//              {
//                //cerr << "statement: " << g_application.GetStatement() << endl; 
//                $$ = $2;
//              } 
//              ; 

statement:     CLEAR_statement
                  {
                    $$ = $1;
                  }
               | DEF_statement
                  {
                    $$ = $1;
                  }   
               | DIM_statement
                  {
                    $$ = $1;
                  }   
               | END_statement
                  {
                    $$ = new AST::End(AST::g_parser->m_lexLineNumber);
                  }   
               | FOR_statement
                  {
                    $$ = $1;
                  }
               | GOTO_statement
                  {
                    $$ = $1;
                  }
               | GOSUB_statement
                  {
                    $$ = $1;
                  }
               | IF_statement
                  {
                    $$ = $1;
                  }
               | INPUT_statement
                  {
                    $$ = $1;
                  }
               | LET_statement
                  {
                    $$ = $1;
                  }
               | LINE_statement
                  {
                    $$ = $1;
                  }
               | NEXT_statement
                  {
                    $$ = $1;
                  }
               | ON_statement
                  {
                    $$ = $1;
                  }   
               | PRINT_statement 
                  {
                    $$ = $1;
                  }
               | REM_statement
                  {
                    $$ = $1;
                  }
               | RUN_statement
                  {
                    $$ = $1;
                  }
               | RETURN_statement
                  {
                    $$ = $1;
                  }
               | STOP_statement
                  {
                    $$ = $1;
                  }
               | SYSTEM_statement
                  {
                    $$ = new AST::System(AST::g_parser->m_lexLineNumber);
                  }
               | WIDTH_statement
                  {
                    $$ = $1;
                  }
               | error /* bison error handler */   
                  {
                    $$ = nullptr;
                  }
               ;

eol:    EOL_TOKEN
        | EOF_TOKEN
          { return 0; }  // yes, this is a return!
        ;               

/********************************************************* 

  CLEAR

 *********************************************************/ 

CLEAR_statement: CLEAR_TOKEN expression
                 {
                   $$ = new AST::Statement(AST::g_parser->m_lexLineNumber);
                 }
                 ;

/********************************************************* 

  DEF

 *********************************************************/ 

DEF_statement:  DEF_TOKEN IDENTIFIER opt_def_args '=' expression 
                {
                  $$ = new AST::Statement(AST::g_parser->m_lexLineNumber);
                }
                ;

opt_def_args: /* empty */
              | '(' def_arg_list ')'
              ;

def_arg_list: IDENTIFIER 
              | def_arg_list ',' IDENTIFIER
              ;              

/********************************************************* 

  DIM

 *********************************************************/ 

DIM_statement:  DIM_TOKEN dim_var_list
                  {
                    $$ = new AST::Statement(AST::g_parser->m_lexLineNumber);
                    //if ($2 != nullptr)
                    //  $$->Append($2);
                  }
                ;

dim_var_list: numeric_var_ref
                {
                  $$ = nullptr;
                }
              | dim_var_list ',' numeric_var_ref 
                {
                  $$ = nullptr;
                }
              ;

/*********************************************************

 END

 *********************************************************/ 
              
END_statement:  END_TOKEN
                ;

/********************************************************* 

 FOR/NEXT/STEP

 *********************************************************/ 

FOR_statement: FOR_TOKEN numeric_var_ref '=' expression TO_TOKEN expression opt_STEP_statement
                {
                  $$ = new AST::ForStatement(AST::g_parser->m_lexLineNumber, $2, $4, $6, $7);
                }
                ;

NEXT_statement: NEXT_TOKEN opt_varname
                {   
                  $$ = new AST::NextStatement(AST::g_parser->m_lexLineNumber, $2);
                }
                ;

opt_varname:    /* empty */
                  {
                    $$ = nullptr;
                  }
                | numeric_var_ref
                  {
                    $$ = $1;
                  }
                ;                

opt_STEP_statement: /* empty */
                      {
                        $$ = nullptr;
                      }
                    | STEP_TOKEN expression
                      {
                        $$ = $2;
                      }
                    ;

/*********************************************************

 GOSUB/RETURN

 *********************************************************/ 
              
GOSUB_statement:  GOSUB_TOKEN line_number
                    {
                      $$ = new AST::GosubStatement(AST::g_parser->m_lexLineNumber, *$2);
                    }
                ;

RETURN_statement:  RETURN_TOKEN
                    {
                      $$ = new AST::ReturnStatement(AST::g_parser->m_lexLineNumber);
                    }
                ;

/*********************************************************

 GOTO

 *********************************************************/ 
              
GOTO_statement: GOTO_TOKEN line_number
                  {
                    $$ = new AST::GotoStatement(AST::g_parser->m_lexLineNumber, *$2);
                    delete $2;
                  }
                ;

/*********************************************************
, 
 IF/THEN/ELSE

 *********************************************************/ 

IF_statement: IF_TOKEN if_expression THEN_TOKEN
                {
                  $<sval>$ = new std::string(g_application.GetStatement());
                  g_application.SetStatementStart();
                }
              conditional_clause opt_ELSE_statement
                {
                  $$ = new AST::IfStatement(AST::g_parser->m_lexLineNumber, $2, $5, $6);
                  $$->m_text = *$<sval>4 + g_application.GetStatement();
                  delete $<sval>4;
                }
              ;

if_expression:  expression 
                  {
                    $$ = $1;
                  }
                | string_compare_expression 
                  {
                    $$ = $1;
                  }
                ;              

opt_ELSE_statement:   /* empty */
                        {
                          $$ = nullptr;
                        }
                      | ELSE_statement
                        {
                          $$ = $1;
                        }
                      ;              

ELSE_statement: ELSE_TOKEN
                  {
                    g_application.SetStatementStart();
                  }
                conditional_clause
                  {
                    $$ = $3;
                  }
                ;

conditional_clause:   line_number
                        {
                          $$ = new AST::IfConditional();
                          $$->m_lineNumber = *$1;
                        }
                      | statement_list
                        {
                          $$ = new AST::IfConditional();
                          $$->m_statements = $1;
                        } 
                      ; 

/********************************************************* 

 INPUT  

 *********************************************************/ 

 LINE_statement:  LINE_TOKEN INPUT_statement
                  {
                    $$ = new AST::Statement(AST::g_parser->m_lexLineNumber);
                  }
                  ;

 INPUT_statement: INPUT_TOKEN QUOTED_STRING ';' input_var_list
                  {
                    $$ = new AST::Statement(AST::g_parser->m_lexLineNumber);
                  }
                  | INPUT_TOKEN input_var_list
                  {
                    $$ = new AST::Statement(AST::g_parser->m_lexLineNumber);
                  }
                  ;

 input_var_list:  input_var
                  | input_var_list ',' input_var
                  ;

 input_var:       numeric_var_ref
                  {
                    UseNumericGlobalVar(*$1, true, false);
                  }
                  | string_var_ref
                  {
                    UseStringGlobalVar(*$1, true, false);
                  }
                  ;       

/********************************************************* 

 LET              

 *********************************************************/ 

LET_statement:  opt_LET_TOKEN assign_expression
                {
                  $$ = new AST::AssignStatement(AST::g_parser->m_lexLineNumber, $2);
                }
                ;

opt_LET_TOKEN:  /* empty */
                | LET_TOKEN
                ;

assign_expression:  numeric_var_ref '=' expression
                      {
                        UseNumericGlobalVar(*$1, true, false);
                        AST::NumericAssign * ass = new AST::NumericAssign($1, $3);
                        ass->Validate();
                        $$ = ass;
                      }
                    
                    | string_var_ref '=' string_expression
                      {
                        UseStringGlobalVar(*$1, true, false);
                        AST::StringAssign * ass = new AST::StringAssign($1, $3);
                        ass->Validate();
                        $$ = ass;
                      }
                    ;

/********************************************************* 

 ON
 
 *********************************************************/ 

ON_statement:    ON_TOKEN expression GOTO_TOKEN line_number opt_on_list
                  {
                    OnRefList * refs = $5;
                    if (refs == nullptr)
                      refs = new OnRefList();
                    refs->push_front(*$4);
                    $$ = new AST::OnGotoStatement(AST::g_parser->m_lexLineNumber, *refs);
                    delete refs;
                  }
                  ;

opt_on_list:     /* empty */
                  {
                    $$ = nullptr;
                  }
                  | ',' line_number opt_on_list
                  {
                    OnRefList * refs = $3;
                    if (refs == nullptr)
                      refs = new OnRefList();
                    refs->push_front(*$2);
                    $$ = refs;
                  }
                  ;                 

/********************************************************* 

 PRINT              
 
 *********************************************************/   

PRINT_statement:  print_keyword
                    {
                    }
                  opt_USING
                    {
                    }  
                  print_expression_list
                    {
                      $$ = new AST::Print(AST::g_parser->m_lexLineNumber, $5);
                    }
                  ;

print_keyword:   PRINT_TOKEN
                 | '?'
                    { 
                    }
                 ;

opt_USING:      /* empty */
                | USING_TOKEN string_expression ';'
                ;                       

print_expression_list: /* empty */
                          {
                            $$ = nullptr;
                          }  
                       | print_expression_list print_expression
                          {
                            if ($1 == nullptr)
                              $1 = new AST::ExprList();
                            $1->Append($2);
                            $$ = $1;
                          }
                       ;

print_expression:      expression
                          {
                            $$ = $1;
                          }
                       | string_expression   
                          {
                            $$ = $1;
                          }
                       | ',' 
                          {
                            $$ = new AST::PrintComma();
                          }
                       | ';'
                          {
                            $$ = new AST::PrintSemiColon();
                          }
                       ;                           

/********************************************************* 

 REM              
 
 *********************************************************/ 

REM_statement: rem_keyword 
                  {
                    MBASIC_SetRemMode();
                  }
                opt_COMMENT
                  {
                    if ($3 == nullptr)
                      $$ = nullptr;
                    else   
                      $$ = new AST::Rem(AST::g_parser->m_lexLineNumber, *$3);
                  }  
               ;

opt_COMMENT:   /* empty */
                  { $$ = nullptr; }
                | COMMENT
                  { $$ = $1; }
                ;                    

rem_keyword: REM_TOKEN
              | '\''
                { 
                  ParserError(eWarning_RemUsingQuote, 
                              "single quote REM not supported in selected language profile"); 
                }
              ;              

/********************************************************* 

 RUN
 
 *********************************************************/ 

RUN_statement: RUN_TOKEN QUOTED_STRING
                  {
                    $$ = new AST::Statement(AST::g_parser->m_lexLineNumber);
                  }
              ;

/********************************************************* 

 STOP              
 
 *********************************************************/ 

STOP_statement: STOP_TOKEN
                {
                  $$ = new AST::Statement(AST::g_parser->m_lexLineNumber);
                }
                ;

/********************************************************* 

 SYSTEM              
 
 *********************************************************/ 

SYSTEM_statement: SYSTEM_TOKEN
                ;

/********************************************************* 

 WIDTH              
 
 *********************************************************/ 

WIDTH_statement: WIDTH_TOKEN integer
                  {
                    $$ = new AST::Statement(AST::g_parser->m_lexLineNumber);
                  }
                  ;

/********************************************************* 

 expression              

 *********************************************************/ 

expression: AND_expression OR_TOKEN expression
              {
                $$ = nullptr;
              }
            | AND_expression
              {
                $$ = $1;
              }  
            ;

AND_expression: NOT_expression AND_TOKEN AND_expression
                  {
                    $$ = nullptr;
                  }
                | NOT_expression
                  {
                    $$ = $1;
                  }
                ;

NOT_expression: '-' numeric_compare_expression
                  {
                    $$ = nullptr;
                  }
                | numeric_compare_expression
                  {
                    $$ = $1;
                  }
                | string_compare_expression  
                  {
                    $$ = nullptr;
                  }
                ;

numeric_compare_expression: ADD_expression '=' numeric_compare_expression
                      {
                        $$ = new AST::NumericEquality($1, $3);
                      }
                    | ADD_expression NOT_EQUAL numeric_compare_expression
                      {
                        $$ = new AST::NumericNotEquality($1, $3);
                      }
                    | ADD_expression '>' numeric_compare_expression
                      {
                        $$ = new AST::NumericGreaterThan($1, $3);
                      }
                    | ADD_expression GREATERTHANEQUAL numeric_compare_expression
                      {
                        $$ = new AST::NumericGreaterThanEqual($1, $3);
                      }
                    | ADD_expression '<' numeric_compare_expression
                      {
                        $$ = new AST::NumericLessThan($1, $3);
                      }
                    | ADD_expression LESSTHANEQUAL numeric_compare_expression
                      {
                        $$ = new AST::NumericLessThanEqual($1, $3);
                      }
                    | ADD_expression 
                      {
                        $$ = $1;
                      }
                    ;

ADD_expression: ADD_expression '+' MULT_expression
                  { 
                    AST::NumericAddition * op = new AST::NumericAddition($1, $3);
                    op->Validate();
                    $$ = op;
                  }
                | ADD_expression '-' MULT_expression
                  { 
                    AST::Subtraction * op = new AST::Subtraction($1, $3);
                    op->Validate();
                    $$ = op;
                  }
                | MULT_expression
                  {
                    $$ = $1;
                  }  
                ;

MULT_expression:  MULT_expression '*' NEGATE_expression
                    { 
                      AST::Multiplication * op = new AST::Multiplication($1, $3);;
                      op->Validate();
                      $$ = op;
                    }
                  | MULT_expression '/' NEGATE_expression
                    { 
                      AST::Division * op = new AST::Division($1, $3);
                      op->Validate();
                      $$ = op;
                    }  
                  | NEGATE_expression
                    {
                      $$ = $1;  
                    } 
                  ;   
                          
NEGATE_expression:  '-' POWER_expression
                      {
                        $$ = new AST::Negation($2);  
                      }
                    | '+' POWER_expression
                      {
                        $$ = $2;  
                      }    
                    | POWER_expression
                      {
                        $$ = $1;
                      }
                    ;  

POWER_expression: POWER_expression '^' subexpression
                    {
                      $$ = new AST::Power($3);
                    }
                  | subexpression
                      {
                        $$ = $1;
                      }
                  ;

subexpression: '(' expression ')'
                  {
                    $$ = $2;
                  }
                | numeric_value
                  {
                    $$ = $1;
                  }
                ;                          

numeric_value:  numeric_var_ref
                  {
                    UseNumericGlobalVar(*$1, false, true);
                    $$ = $1;
                  }
                | INT_TOKEN '(' expression ')'  
                  {
                    $$ = new AST::IntFunction($3);
                  }
                | SQR_TOKEN '(' expression ')'  
                  {
                    $$ = new AST::SqrFunction($3);
                  }
                | LEN_TOKEN '(' string_expression ')'  
                  {
                    cout << "creating LEN" << endl;
                    $$ = new AST::LenFunction($3);
                  }
                | ABS_TOKEN '(' expression ')'  
                  {
                    $$ = new AST::AbsFunction($3);
                  }
                | RND_TOKEN '(' expression ')'  
                  {
                    $$ = new AST::RndFunction($3);
                  }

                | numeric_const_expr
                  {
                    $$ = $1;
                  }
                ;  

/********************************************************* 

 string expression              

 *********************************************************/ 

string_compare_expression: string_expression '=' string_expression
                      {
                        $$ = nullptr;
                      }
                    | string_expression NOT_EQUAL string_expression
                      {
                        $$ = nullptr;
                      }
                    ;  
                      
string_expression: string_subexpression '+' string_expression
                        { 
                          $$ = new AST::StringAddition($1, $3);
                        }
                       | string_subexpression 
                        { 
                          $$ = $1;
                        }
                      ;

string_subexpression: '(' string_expression ')'
                  {
                    $$ = $2;
                  }
                | string_value
                  {
                    $$ = $1;
                  }
                ;

string_value:   string_var_ref
                  {
                    $$ = $1;
                    UseStringGlobalVar(*$1, false, true);
                  }
                | CHR_TOKEN '(' expression ')'  
                  {
                    $$ = new AST::ChrFunction($3);
                  }
                | LEFT_TOKEN '(' string_expression ',' expression ')'  
                  {
                    $$ = new AST::LeftFunction($3, $5);
                  }
                | MID_TOKEN '(' string_expression ',' expression ',' expression ')'  
                  {
                    $$ = new AST::MidFunction($3, $5, $7);
                  }
                | RIGHT_TOKEN '(' string_expression ',' expression ')'  
                  {
                    $$ = new AST::RightFunction($3, $5);
                  }
                | STR_TOKEN '(' expression ')'  
                  {
                    $$ = new AST::StrFunction($3);
                  }                  
                | TAB_TOKEN '(' expression ')'  
                  {
                    $$ = new AST::TabFunction($3);
                  }
                | string_const_expr
                  {
                    $$ = $1;
                  }
                ;  

/********************************************************* 

numeric var or numeric array ref              
 
 *********************************************************/

numeric_var_ref : numeric_var_name
            {
              $$ = $1;
            }
          | numeric_var_name array_or_func_spec
            {
            }
          ;

numeric_var_name: IDENTIFIER
            {
              $$ = new AST::NumericVarRef(AST::g_parser->m_languageProfile->GetDefaultNumericType(), *$1);
              delete $1;
            }
          | INTEGER_VARNAME
            {
              $$ = new AST::NumericVarRef(AST::g_parser->m_languageProfile->GetIntegerType(), *$1);
              delete $1;
            }
          | SINGLE_VARNAME
            {
              $$ = new AST::NumericVarRef(VarType::eSingle, *$1);
              delete $1;
            }
          | DOUBLE_VARNAME
            {
              $$ = new AST::NumericVarRef(VarType::eDouble, *$1);
              delete $1;
            }
          ;

string_var_ref : string_var_name
                  {
                    $$ = $1;
                  }
                | string_var_name array_or_func_spec
                  {
                  }
                ;

string_var_name: STRING_VARNAME
            {
              $$ = new AST::StringVarRef(*$1);
              delete $1;
            }
            ;

array_or_func_spec: '(' array_or_func_args ')'
                      {
                      }
                    ; 

array_or_func_args: array_or_func_arg 
                      {
                      }
                    | array_or_func_args ',' array_or_func_arg   
                      {
                      }
                    ;

array_or_func_arg:  expression
                      {
                      }
                    /*| string_expression
                      {
                      }
                    */
                    ;

/********************************************************* 

 miscellaneous              
 
 *********************************************************/ 

numeric_const_expr: INTEGER
              {
                stringstream strm;
                strm << $1;
                $$ = CreateConstant(AST::g_parser->m_languageProfile->GetIntegerType(), strm.str());
              }
            | DEF_INTEGER  
              {
                // count significant digits
                int s = 0;
                for (auto & c : *$1)
                  if (isdigit(c))
                    s++;
                int32_t v = strtoul($1->c_str(), nullptr, 10);
                if (
                    (AST::g_parser->m_languageProfile->GetDefaultNumericType() == VarType::eInt16) && 
                    (v <= 32767) && 
                    (v >= -32768)
                   ) {
                  $$ = CreateConstant(VarType::eInt16, *$1);
                }
                else if (
                    (AST::g_parser->m_languageProfile->GetDefaultNumericType() == VarType::eInt32) && 
                    (v <= 2147483647) && 
                    (v >= -214748368)
                  ) {
                  $$ = CreateConstant(VarType::eInt32, *$1);
                } 
                else if (s <= 7) {
                  $$ = CreateConstant(VarType::eSingle, *$1);
                }
                else {
                  $$ = CreateConstant(VarType::eDouble, *$1);
                }
                delete $1;
              }
            | DOUBLE
              {
                $$ = new AST::DoubleConstant($1->m_value);
                delete $1;
              }
            | SINGLE
              {
                $$ = new AST::SingleConstant($1->m_value);
                delete $1;
              }
            ;

string_const_expr: QUOTED_STRING
              {
                $$ = new AST::StringConstant(*$1);
                delete $1;
              }
            ;
