#!/bin/bash

RUN_CPM="${HOME}/gratze/emulator/gratze --type cpm80 --turbo "
MBASIC_CPM="${RUN_CPM} ${HOME}/gratze/emulator/Mbasic.com"
BASALT="${HOME}/basalt/basalt"

function TestCPM()
{
  local fn=$1
  local out=$2
  $MBASIC_CPM $fn | sed "0,/^--START/d" > $out
}

function TestANSIC()
{
  local fn=$1
  local out=$2

  $BASALT -a ansi-c -o ${out}.c $fn && \
  gcc ${out}.c -o ${out}.bin -L.. -lbasaltrt
  ./${out}.bin | sed "0,/^--START/d" > $out
}

function TestZ80()
{
  local fn=$1
  local out=$2

  $BASALT -a z80 -o ${out}.asm $fn && \
  z80asm -o ${out}.com ${out}.asm
  ${RUN_CPM} ${out}.com | sed "0,/^--START/d" > $out
}

function run_test()
{
  local num=$1
  local bas=test_${num}.bas
  local cpm=cpm_${num}_out
  local ansic=ansic_${num}_out
  local z80=z80_${num}_out

  echo "Test $num"

  echo '1 print "--START--"' > $bas
  cat - >> $bas
  echo '9999 system' >> $bas

  TestCPM $bas $cpm
  TestANSIC $bas $ansic
  TestZ80 $bas $z80
  cmp $cpm $ansic
  cmp $cpm $z80
}

##########################

cat <<EOF | run_test 1
10 print "hello, world"
20 print "hello" ; "world"
30 print "hello" , "world"
40 print "hello" , "world" ;
50 print "continue"
EOF

cat <<EOF | run_test 2
5 print "0" ; 0
6 print "1" ; 1
7 print "-1" ; -1
10 print "-4567" ; -4567
30 print "4567" ; 4567
40 print "-32768" ; -32768
50 print "-32767" ; -32767
60 print "32767" ; 32767
71 print "32768" ; 32768
80 print "100000" ; 100000
90 print "-100000" ; -100000
100 print "2147483647" ; 2147483647
101 print "2147483648" ; 2147483648
110 print "-2147483647" ; -2147483647
111 print "-2147483648" ; -2147483648
EOF

cat <<EOF | run_test 3
10 print "start"
20 goto 50
30 print "step 3"
40 goto 70
50 print "step 2"
60 goto 30
70 print "end"
EOF

cat <<EOF | run_test 4
10 a = 1 : print a
20 a = 1234 : print a
EOF
